version: '3.4'

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile_nginx
    ports:
      - '95:95'
    container_name: 'nginx_php_store'
    links:
      - php_app
    networks:
      - app-network

  php_app:
    container_name: 'app_php_store'
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_php
    volumes:
    - ./:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-php
    env_file:
      - ./.env
    ports:
      - '3305:3306'
    expose:
      - 3305
    command: [ --ddefault-authentication-plugin=mysql_native_password ]
    volumes:
      - ./config/db/:/docker-entrypointdb.d
    networks:
      - app-network

networks:
 app-network:
  driver: bridge