FROM php:8.0.2-fpm

COPY . /php_store_app

ARG uid=1000
ARG user=marcos_dev

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo

RUN ["chmod", "+x", "/php_store_app/scripts/config/docker_php_conf.sh"]

RUN ["bash", "/php_store_app/scripts/config/docker_php_conf.sh"]

CMD ["php-fpm"]