-- MySQL Script generated by MySQL Workbench
-- Sat Aug  8 13:26:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema php_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_store` DEFAULT CHARACTER SET utf8 ;
USE `php_store` ;

-- -----------------------------------------------------
-- Table `php_store`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_store`.`loja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(25) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_store`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_store`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_loja` INT NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `nick_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `data_nasc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `id_loja`),
  UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC) VISIBLE,
  INDEX `fk_usuario_loja_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_loja`
    FOREIGN KEY (`id_loja`)
    REFERENCES `php_store`.`loja` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO loja(nome, razao_social, cnpj, cidade, estado) VALUES ("Adminstore", "Loja de Administração", 8080127001, "Florianópolis", "Santa Catarina");

INSERT INTO usuario(id_loja, role, nick_name, password, data_nasc) VALUES (1, "admin", "admin", "admin", 1999-07-30);

INSERT INTO usuario(id_loja, role, nick_name, password, data_nasc) VALUES (1, "user", "user", "user", 1999-07-30);